name: "000_STFAN_seq20_lr2e4_DVD_e651_B1G2_s"

__base_cfg__: ./../../base_dvd.yaml

model:
    name: "STFAN"

loss: 
    name: CharbonnierLoss

schedule: 
    epochs: 651
    val_epochs: 5
    
    optimizer:
        name: "Adam"
        lr: 0.0002
        betas: [0.9, 0.99]
        weight_decay: 0
        
    lr_scheduler:
        name: "MultiStepLR"
        milestones: [500, 600, 620]
        gamma: 0.1

logging: 
    period: 20

ckpt:
    period: 10


work_dir: "./workdir/stfan"
resume_from: None