name: "000_IFIRNN_C2H3_lr2e4_DVD_e651_B8G4_s"

__base_cfg__: ./../../base_dvd.yaml


model:
    name: "IFIRNN"
    in_channels: 3
    inner_channels: 16
    dual_cell: True
    intra_iters: 3

loss: 
    name: CharbonnierLoss

schedule: 
    epochs: 651
    val_epochs: 5
    
    optimizer:
        name: "Adam"
        lr: 0.0002
        betas: [0.9, 0.99]
        weight_decay: 0
        
    lr_scheduler:
        name: "MultiStepLR"
        milestones: [500, 600, 620]
        gamma: 0.1

logging: 
    period: 20

ckpt:
    period: 10


work_dir: "./workdir/IFIRNN"
resume_from: None
